---
apiVersion: v1
kind: Namespace
metadata:
  name: thealoecompany
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: travis
  namespace: thealoecompany
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: travis
  namespace: thealoecompany
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travis
  namespace: thealoecompany
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: travis
subjects:
- kind: ServiceAccount
  name: travis
  namespace: thealoecompany
