nameOverride: thealoecompany
pods:
  image:
    name: ghcr.io/smirl/thealoecompany
    tag: 1.0.0
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  ports:
    - containerPort: 80
      name: http
  env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: amplify
          key: api_key
    - name: AMPLIFY_IMAGENAME
      value: 'thealoecompany'

podDisruptionBudget:
  enabled: false

service:
  enabled: true
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http

ingress:
  enabled: true
  annotations:
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hosts:
    - thealoecompany.com
    - www.thealoecompany.com
  tls:
    - hosts:
        - thealoecompany.com
        - www.thealoecompany.com
      secretName: thealoecompany-tls
