name: Deploy

on:
  push:
    tags:
      - v*
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/smirl/thealoecompany

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://thealoecompany.com/
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # DEPLOY
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1

      - name: Helm tool installer
        uses: Azure/setup-helm@v1
        with:
          version: '3.2.4'

      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_URL }}
          k8s-secret: ${{ secrets.K8S_SECRET }}

      - name: Helm repo add mvisonneau
        run: helm repo add mvisonneau https://charts.visonneau.fr/

      - name: Deploy
        run: helm upgrade --install thealoecompany mvisonneau/generic-app --version 0.0.11 --namespace thealoecompany -f deploy/values.yaml --set pods.image.tag=$GIT_TAG_NAME
